name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - services/**
      - .github/workflows/test.yaml
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      # - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Paths Changes Filter
        id: filter
        # uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml
  test:
    runs-on: ubuntu-24.04
    needs: filter
    strategy:
      fail-fast: false
      matrix:
        # service:
        #   [
        #     # "services/node/api-node",
        #     # "services/go/api-golang",
        #     # "services/react/client-react",
        #     "services/python/load-generator-python",
        #   ]
        service: ${{ fromJson( needs.filter.outputs.services ) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        if: ${{ startsWith( matrix.service, 'services/node/' ) || startsWith(
          matrix.service, 'services/react/' ) }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        # TODO: use specified version + setup caching
        with:
          node-version-file: ${{ matrix.service }}/package.json
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json
      - name: Setup go
        if: ${{ startsWith( matrix.service, 'services/go/' ) }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum
      - name: Install poetry
        if: ${{ startsWith( matrix.service, 'services/python/' ) }}
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      - name: Setup python
        if: ${{ startsWith( matrix.service, 'services/python/' ) }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version-file: ${{ matrix.service }}/pyproject.toml
          cache: poetry
          cache-dependency-path: ${{ matrix.service }}/poetry.lock
      - name: Install task
        uses: supplypike/setup-bin@8e3f88b4f143d9b5c3497f0fc12d45c83c123787 # v4.0.1
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.50.0/task_linux_amd6\
            4.tar.gz"
          name: task
          version: v3.50.0
      - name: Install node deps
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci
      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: |
          task test
  # run-tests:
  #   runs-on: ubuntu-24.04
  #   if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services
  #     != '' }}
  #   needs: filter
  #   strategy:
  #     matrix:
  #       service: ${{ fromJson(needs.filter.outputs.services) }}
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
  #     - uses: ./.github/actions/setup-dependencies
  #       with:
  #         install_task: "true"
  #         install_go: ${{ startsWith(matrix.service, 'services/go/') }}
  #         install_node: ${{ startsWith(matrix.service, 'services/node/') ||
  #           startsWith(matrix.service, 'react/') }}
  #         install_python: ${{ startsWith(matrix.service, 'services/python/') }}
  #         service_path: ${{ matrix.service }}
  #     - name: Install / Build
  #       working-directory: ${{ matrix.service }}
  #       run: |
  #         task install-ci
  #     - name: run tests
  #       working-directory: ${{ matrix.service }}
  #       run: |
  #         task test

  # # This job gets skipped if all upstream jobs succeeded, but it runs (and fails) if any upstream failed.
  # # This is what we want since GitHub required actions do not block merging when skipped, but can block it when failed.
  # # See: https://github.com/actions/runner/issues/2566#issuecomment-3053484216
  # run-tests-failure-alert:
  #   runs-on: ubuntu-latest
  #   needs: [ filter, run-tests ]
  #   if: ${{ cancelled() || contains(needs.*.result, 'cancelled') ||
  #     contains(needs.*.result, 'failure') }}
  #   steps:
  #     - name: Conditionally Fail Required Check
  #       shell: bash
  #       run: |
  #         echo "::error Some required job has failed!"
  #         exit 1
